on: push

name: Integration

jobs:
  build:
    strategy:
      matrix:
        os: 
        - ubuntu-latest
        - macos-latest
        - windows-latest
        go-version:
        - 1.16
        - 1.17
        - 1.18
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - shell: bash
        run: |
          go build -o myapp
          go test
          ./myapp &
          res=$(curl localhost:3000)
          [[ $res == 'Hello, World!' ]] 
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build .      
