on: 
  push:
    tags:
      - "**"

name: Release

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env: 
      DOCKER_REPOSITORY: samfrancis/cd
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: |
          version=${GITHUB_REF##*/}
          docker build . -t $DOCKER_REPOSITORY:$version
      - name: Push Docker Image
        run: |
          version=${GITHUB_REF##*/}
          docker push $DOCKER_REPOSITORY:$version
      - name: This is test
        run: |
         echo "test second steps"
      - name: This is test 2
        run: |
          echo "This third steps"
